# Generated by Django 5.2.8 on 2026-02-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carmodels_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='category',
        ),
        migrations.AddField(
            model_name='carmodels',
            name='fuel',
            field=models.CharField(default=1, max_length=100, verbose_name='топливо'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='image',
            field=models.ImageField(upload_to='cars/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='name',
            field=models.CharField(max_length=100, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='price',
            field=models.CharField(max_length=100, verbose_name='цена'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
