# Generated by Django 5.2.8 on 2026-02-09 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_carmodels_category_carmodels_fuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('vin', models.CharField(max_length=255, unique=True, verbose_name='VIN-code')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('fuel', models.CharField(max_length=255, verbose_name='Fuel')),
                ('gearbox', models.CharField(max_length=255, verbose_name='Gearbox')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('car_body', models.CharField(max_length=255, verbose_name='Car Body')),
                ('drive', models.CharField(max_length=255, verbose_name='Drive')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Volume')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subcategory_icons/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='api.category')),
            ],
        ),
        migrations.DeleteModel(
            name='CarModels',
        ),
    ]
