# Generated by Django 5.2.8 on 2026-02-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_products_subcategory_delete_carmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Price'),
        ),
    ]
