# Generated by Django 5.2.8 on 2026-02-12 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_subcategory_model_products_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='info',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='Info'),
            preserve_default=False,
        ),
    ]
