# Generated by Django 5.2.8 on 2026-02-12 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subcategory_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='fuel_info',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Fuel_info'),
            preserve_default=False,
        ),
    ]
