# Generated by Django 5.2.8 on 2026-02-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subcategory_fuel_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='products',
            name='year',
        ),
    ]
