# Generated by Django 5.2.8 on 2026-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_products_amount_remove_products_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Price'),
        ),
    ]
