# Generated by Django 5.2.8 on 2026-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='volume',
            field=models.CharField(max_length=255, verbose_name='Volume'),
        ),
    ]
