# Generated by Django 5.2.8 on 2026-02-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_products_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price'),
        ),
    ]
