# Generated by Django 5.2.8 on 2026-02-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Division')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='api.footer')),
            ],
        ),
    ]
